### PR TITLE
Fixes #86 - bug: Fix radio button state not being rendered correctly

### LINKED ISSUE #86: Fix Demographic Survey Pre-Checked Style Bug
In the later part of the survey, the radio buttons are preselected when the answers from the previous question are the same. 
image

This task is to fix the styling so that the styling gets reset on each new question.

### PR DESCRIPTION
**Pull request by franciscocha**

### CODE REVIEW

**Review by avenmia — APPROVED** [review]
lgtm! :shipit:

File: src/components/survey/demographicssurvey.tsx [hunk 1]
```diff
@@ -111,7 +111,7 @@ export default function DemographicsSurvey() {
           document.getElementsByClassName("form-radio")
         );
         radioButtonArray.forEach((el: Element) => {
-          el.checked = false;
+          (el as HTMLInputElement).checked = false;
```
Comment (kmal808) [inline src/components/survey/demographicssurvey.tsx:114]: :eyes: 🍒
