### PR TITLE
avenmia/check if user entered census data

### LINKED ISSUE #32: Check if the user exists and has entered their census tract data
At the moment, if the user is on the census tract page, it doesn't matter if they filled it out before they're required to fill it out again. 

This task is for adding a check if the user exists and if they have an existing census tract in the database. If they do, confirm the census tract is correct (Ideally, highlight the census tract on the map). If the user says it is incorrect, display the census tract map for the user to reenter their census tract information.

### PR DESCRIPTION
**Pull request by avenmia**
If a user has already added their census tract data, they are presented with a screen that shows their previous choice as well as the button that lets them go to the next screen

closes #32

### CODE REVIEW

File: src/components/existingcensusmap.tsx [hunk 1]
```diff
@@ -6,7 +6,7 @@ interface ExistingCensusMapProps {
 export default function ExistingCensusMap({existingCensusTract}: ExistingCensusMapProps ) {
   return (
     <>
-      <h1 className="text-white">User's existing census tract is: {existingCensusTract}</h1>
+      <h1 className="text-white">User`&apos;s existing census tract is: {existingCensusTract}</h1>
```
Comment (kmal808) [inline src/components/existingcensusmap.tsx:9]:
```suggestion
      <h1 className="text-white">User&apos;s existing census tract is: {existingCensusTract}</h1>

**Review by kmal808 — APPROVED** [review]
Other than the rouge backtick, works as described. Cherry brah 🍒 
🚢 🚀
